FROM fedora
RUN dnf install -y openssh-server sudo python3
RUN ssh-keygen -A
RUN echo 'root:password' | chpasswd
RUN mkdir -p /root/.ssh
COPY id_ed25519.pub /root/.ssh/authorized_keys
RUN chmod 600 /root/.ssh/authorized_keys
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]